language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false
jobs:

  include:
    # This builder only tests code linters on latest version of Go
    - stage: lint
      os: linux
      dist: xenial
      go: 1.15.x
      env:
        - lint
      git:
        submodules: false # avoid cloning ethereum/tests
      script:
        - go run build/ci.go lint

    # These builders run the tests
    - stage: build
      os: linux
      arch: amd64
      dist: xenial
      go: 1.15.x
      env:
        - GO111MODULE=on
      script:
        - go run build/ci.go test -coverage $TEST_PACKAGES

    - stage: build
      if: type = pull_request
      os: linux
      arch: arm64
      dist: xenial
      go: 1.15.x
      env:
        - GO111MODULE=on
      script:
        - go run build/ci.go test -coverage $TEST_PACKAGES

    - stage: build
      os: linux
      dist: xenial
      go: 1.14.x
      env:
        - GO111MODULE=on
      script:
        - go run build/ci.go test -coverage $TEST_PACKAGES
